# // TODO: Implementar el docker-compose

version: '3.8'

services:
  libreria-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreria-app
    ports:
      - "8080:8080"
    volumes:
      - h2_data:/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/libreria_db
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
    restart: unless-stopped
    networks:
      - libreria-network

networks:
  libreria-network:
    driver: bridge

volumes:
  h2_data:
    driver: local